
class Py3oException(Exception):
    pass